name: openseestools
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - anaconda
  - matplotlib
  - numpy
  - pandas>=1.0
  - tabulate
  - pip
  - pip:
    - openseespy
    - "-e ."
  # Development
  - ipython
  - line_profiler
  - yapf
  - pytest
  - invoke
  - sphinx
  - sphinx_rtd_theme
  - docutils
  - doc8
