name: OpenSeesTools
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - numpy
  - tabulate
  - pip
  - pip:
    - openseespy
    - "-e ."
  # Development
  - ipython
  - line_profiler
  - yapf
  - pytest
  - invoke
  - sphinx
  - sphinx_rtd_theme
  - docutils
  - doc8
